### ISSUE TITLE
[Tumbleweed] can't get libdl.so

### ISSUE THREAD

**Issue by d3vilguard** [benjamimgois/goverlay#175] opened 2021-12-25 13:39 UTC
Latest Tumbleweed. Installing with **zypper in goverlay**

```
d3vil@openSUSE:~> goverlay
can't get libdl.so

```

**Comment by kevinsmia1939** [comment] 2021-12-26 23:07
likely duplicate of this https://github.com/benjamimgois/goverlay/issues/156

**Comment by kevinsmia1939** [comment] 2022-03-16 22:16
I think we can close this too because #156 .

**Comment by benjamimgois** [comment] 2022-03-17 00:36
Ok, thanks !

**Closed by benjamimgois** 2022-03-17 00:36 UTC
